spring:
  jpa:    hibernate:      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
       hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:    hikari:      connection-timeout: 5000
      validation-timeoit: 1000
      maximum-pool-size: 30
    driver-class-name: org.mariadb.jdbc.Driver  
    url: jdbc:mariadb://192.168.0.26/redistest
    username: yjy
    password: yjy  
logging:  level:    root: warn
    com.yoon.Security_Jwt_Redis: debug  